version: 2

# Set the OS and Python version
build:
  os: ubuntu-22.04
  tools:
    python: "3.12"

python:
  install:
    # 1. Install all dependencies, including Sphinx and h5py/numpy, from requirements.txt
    - requirements: docs/requirements.txt
    
    # # 2. Install the local packages in editable mode
    - method: pip
      path: packages/pack_HDF5_BLS


    - method: pip
      path: packages/pack_HDF5_BLS_analyse

    - method: pip
      path: packages/pack_HDF5_BLS_treat

# Build documentation in the "docs/" directory with Sphinx
sphinx:
  configuration: docs/conf.py

# Optionally build your docs in additional formats such as PDF and ePub
formats:
  - pdf
  - epub